export const PROJECT_WIDTH = 140
export const PROJECT_HEIGHT = 140

export const PROJECT_MARGIN = 10

export const PROJECT_FULL_WIDTH = PROJECT_WIDTH+ 2 * PROJECT_MARGIN
export const PROJECT_FULL_HEIGHT = PROJECT_HEIGHT + 2 * PROJECT_MARGIN