//--------------SETTINGS-ACTIONS--------------//

export const ST_SET_LANGUAGE = 'ST_SET_LANGUAGE'
export const ST_SET_THEME = 'ST_SET_THEME'

//--------------AUTH-ACTIONS--------------//

export const AUTH_SET_AUTHENTICATED = 'AUTH_SET_AUTHENTICATED'
export const AUTH_SET_USER_DATA = 'AUTH_SET_USER_DATA'
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN'
export const AUTH_SET_LOADING = 'AUTH_SET_LOADING'
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR'
export const AUTH_SET_NOTICE = 'AUTH_SET_NOTICE'


//--------------PROJECTS-ACTIONS--------------//

export const PRJCTS_SET_PROJECTS = 'PRJCTS_SET_PROJECTS'
export const PRJCTS_SET_IS_PROJECTS_LOADING = 'PRJCTS_SET_IS_PROJECTS_LOADING'
export const PRJCTS_SET_IS_PROJECTS_SENDING = 'PRJCTS_SET_IS_PROJECTS_SENDING'
export const PRJCTS_SET_IS_NOTIFICATION = 'PRJCTS_SET_IS_NOTIFICATION'

